// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/TestEntity.proto

package proto;

public final class TestEntityOuterClass {
  private TestEntityOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TestEntityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.TestEntity)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string name2 = 2;</code>
     * @return The name2.
     */
    java.lang.String getName2();
    /**
     * <code>string name2 = 2;</code>
     * @return The bytes for name2.
     */
    com.google.protobuf.ByteString
        getName2Bytes();

    /**
     * <code>int64 longNum = 3;</code>
     * @return The longNum.
     */
    long getLongNum();

    /**
     * <code>int64 longNum2 = 4;</code>
     * @return The longNum2.
     */
    long getLongNum2();

    /**
     * <code>int32 intNum = 5;</code>
     * @return The intNum.
     */
    int getIntNum();

    /**
     * <code>int32 intNum2 = 6;</code>
     * @return The intNum2.
     */
    int getIntNum2();

    /**
     * <code>double doubleNum = 7;</code>
     * @return The doubleNum.
     */
    double getDoubleNum();

    /**
     * <code>double doubleNum2 = 8;</code>
     * @return The doubleNum2.
     */
    double getDoubleNum2();

    /**
     * <code>int64 localDate = 9;</code>
     * @return The localDate.
     */
    long getLocalDate();

    /**
     * <code>int64 localDateTime = 10;</code>
     * @return The localDateTime.
     */
    long getLocalDateTime();
  }
  /**
   * Protobuf type {@code protocol.TestEntity}
   */
  public static final class TestEntity extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.TestEntity)
      TestEntityOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TestEntity.newBuilder() to construct.
    private TestEntity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TestEntity() {
      name_ = "";
      name2_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TestEntity();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TestEntity(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name2_ = s;
              break;
            }
            case 24: {

              longNum_ = input.readInt64();
              break;
            }
            case 32: {

              longNum2_ = input.readInt64();
              break;
            }
            case 40: {

              intNum_ = input.readInt32();
              break;
            }
            case 48: {

              intNum2_ = input.readInt32();
              break;
            }
            case 57: {

              doubleNum_ = input.readDouble();
              break;
            }
            case 65: {

              doubleNum2_ = input.readDouble();
              break;
            }
            case 72: {

              localDate_ = input.readInt64();
              break;
            }
            case 80: {

              localDateTime_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.TestEntityOuterClass.internal_static_protocol_TestEntity_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.TestEntityOuterClass.internal_static_protocol_TestEntity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.TestEntityOuterClass.TestEntity.class, proto.TestEntityOuterClass.TestEntity.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME2_FIELD_NUMBER = 2;
    private volatile java.lang.Object name2_;
    /**
     * <code>string name2 = 2;</code>
     * @return The name2.
     */
    @java.lang.Override
    public java.lang.String getName2() {
      java.lang.Object ref = name2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name2_ = s;
        return s;
      }
    }
    /**
     * <code>string name2 = 2;</code>
     * @return The bytes for name2.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getName2Bytes() {
      java.lang.Object ref = name2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LONGNUM_FIELD_NUMBER = 3;
    private long longNum_;
    /**
     * <code>int64 longNum = 3;</code>
     * @return The longNum.
     */
    @java.lang.Override
    public long getLongNum() {
      return longNum_;
    }

    public static final int LONGNUM2_FIELD_NUMBER = 4;
    private long longNum2_;
    /**
     * <code>int64 longNum2 = 4;</code>
     * @return The longNum2.
     */
    @java.lang.Override
    public long getLongNum2() {
      return longNum2_;
    }

    public static final int INTNUM_FIELD_NUMBER = 5;
    private int intNum_;
    /**
     * <code>int32 intNum = 5;</code>
     * @return The intNum.
     */
    @java.lang.Override
    public int getIntNum() {
      return intNum_;
    }

    public static final int INTNUM2_FIELD_NUMBER = 6;
    private int intNum2_;
    /**
     * <code>int32 intNum2 = 6;</code>
     * @return The intNum2.
     */
    @java.lang.Override
    public int getIntNum2() {
      return intNum2_;
    }

    public static final int DOUBLENUM_FIELD_NUMBER = 7;
    private double doubleNum_;
    /**
     * <code>double doubleNum = 7;</code>
     * @return The doubleNum.
     */
    @java.lang.Override
    public double getDoubleNum() {
      return doubleNum_;
    }

    public static final int DOUBLENUM2_FIELD_NUMBER = 8;
    private double doubleNum2_;
    /**
     * <code>double doubleNum2 = 8;</code>
     * @return The doubleNum2.
     */
    @java.lang.Override
    public double getDoubleNum2() {
      return doubleNum2_;
    }

    public static final int LOCALDATE_FIELD_NUMBER = 9;
    private long localDate_;
    /**
     * <code>int64 localDate = 9;</code>
     * @return The localDate.
     */
    @java.lang.Override
    public long getLocalDate() {
      return localDate_;
    }

    public static final int LOCALDATETIME_FIELD_NUMBER = 10;
    private long localDateTime_;
    /**
     * <code>int64 localDateTime = 10;</code>
     * @return The localDateTime.
     */
    @java.lang.Override
    public long getLocalDateTime() {
      return localDateTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name2_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name2_);
      }
      if (longNum_ != 0L) {
        output.writeInt64(3, longNum_);
      }
      if (longNum2_ != 0L) {
        output.writeInt64(4, longNum2_);
      }
      if (intNum_ != 0) {
        output.writeInt32(5, intNum_);
      }
      if (intNum2_ != 0) {
        output.writeInt32(6, intNum2_);
      }
      if (java.lang.Double.doubleToRawLongBits(doubleNum_) != 0) {
        output.writeDouble(7, doubleNum_);
      }
      if (java.lang.Double.doubleToRawLongBits(doubleNum2_) != 0) {
        output.writeDouble(8, doubleNum2_);
      }
      if (localDate_ != 0L) {
        output.writeInt64(9, localDate_);
      }
      if (localDateTime_ != 0L) {
        output.writeInt64(10, localDateTime_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name2_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name2_);
      }
      if (longNum_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, longNum_);
      }
      if (longNum2_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, longNum2_);
      }
      if (intNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, intNum_);
      }
      if (intNum2_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, intNum2_);
      }
      if (java.lang.Double.doubleToRawLongBits(doubleNum_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, doubleNum_);
      }
      if (java.lang.Double.doubleToRawLongBits(doubleNum2_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, doubleNum2_);
      }
      if (localDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, localDate_);
      }
      if (localDateTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, localDateTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.TestEntityOuterClass.TestEntity)) {
        return super.equals(obj);
      }
      proto.TestEntityOuterClass.TestEntity other = (proto.TestEntityOuterClass.TestEntity) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getName2()
          .equals(other.getName2())) return false;
      if (getLongNum()
          != other.getLongNum()) return false;
      if (getLongNum2()
          != other.getLongNum2()) return false;
      if (getIntNum()
          != other.getIntNum()) return false;
      if (getIntNum2()
          != other.getIntNum2()) return false;
      if (java.lang.Double.doubleToLongBits(getDoubleNum())
          != java.lang.Double.doubleToLongBits(
              other.getDoubleNum())) return false;
      if (java.lang.Double.doubleToLongBits(getDoubleNum2())
          != java.lang.Double.doubleToLongBits(
              other.getDoubleNum2())) return false;
      if (getLocalDate()
          != other.getLocalDate()) return false;
      if (getLocalDateTime()
          != other.getLocalDateTime()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + NAME2_FIELD_NUMBER;
      hash = (53 * hash) + getName2().hashCode();
      hash = (37 * hash) + LONGNUM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLongNum());
      hash = (37 * hash) + LONGNUM2_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLongNum2());
      hash = (37 * hash) + INTNUM_FIELD_NUMBER;
      hash = (53 * hash) + getIntNum();
      hash = (37 * hash) + INTNUM2_FIELD_NUMBER;
      hash = (53 * hash) + getIntNum2();
      hash = (37 * hash) + DOUBLENUM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getDoubleNum()));
      hash = (37 * hash) + DOUBLENUM2_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getDoubleNum2()));
      hash = (37 * hash) + LOCALDATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLocalDate());
      hash = (37 * hash) + LOCALDATETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLocalDateTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.TestEntityOuterClass.TestEntity parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.TestEntityOuterClass.TestEntity parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.TestEntityOuterClass.TestEntity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.TestEntityOuterClass.TestEntity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.TestEntityOuterClass.TestEntity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.TestEntityOuterClass.TestEntity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.TestEntityOuterClass.TestEntity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.TestEntityOuterClass.TestEntity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.TestEntityOuterClass.TestEntity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.TestEntityOuterClass.TestEntity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.TestEntityOuterClass.TestEntity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.TestEntityOuterClass.TestEntity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.TestEntityOuterClass.TestEntity prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.TestEntity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.TestEntity)
        proto.TestEntityOuterClass.TestEntityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.TestEntityOuterClass.internal_static_protocol_TestEntity_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.TestEntityOuterClass.internal_static_protocol_TestEntity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.TestEntityOuterClass.TestEntity.class, proto.TestEntityOuterClass.TestEntity.Builder.class);
      }

      // Construct using proto.TestEntityOuterClass.TestEntity.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        name2_ = "";

        longNum_ = 0L;

        longNum2_ = 0L;

        intNum_ = 0;

        intNum2_ = 0;

        doubleNum_ = 0D;

        doubleNum2_ = 0D;

        localDate_ = 0L;

        localDateTime_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.TestEntityOuterClass.internal_static_protocol_TestEntity_descriptor;
      }

      @java.lang.Override
      public proto.TestEntityOuterClass.TestEntity getDefaultInstanceForType() {
        return proto.TestEntityOuterClass.TestEntity.getDefaultInstance();
      }

      @java.lang.Override
      public proto.TestEntityOuterClass.TestEntity build() {
        proto.TestEntityOuterClass.TestEntity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.TestEntityOuterClass.TestEntity buildPartial() {
        proto.TestEntityOuterClass.TestEntity result = new proto.TestEntityOuterClass.TestEntity(this);
        result.name_ = name_;
        result.name2_ = name2_;
        result.longNum_ = longNum_;
        result.longNum2_ = longNum2_;
        result.intNum_ = intNum_;
        result.intNum2_ = intNum2_;
        result.doubleNum_ = doubleNum_;
        result.doubleNum2_ = doubleNum2_;
        result.localDate_ = localDate_;
        result.localDateTime_ = localDateTime_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.TestEntityOuterClass.TestEntity) {
          return mergeFrom((proto.TestEntityOuterClass.TestEntity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.TestEntityOuterClass.TestEntity other) {
        if (other == proto.TestEntityOuterClass.TestEntity.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getName2().isEmpty()) {
          name2_ = other.name2_;
          onChanged();
        }
        if (other.getLongNum() != 0L) {
          setLongNum(other.getLongNum());
        }
        if (other.getLongNum2() != 0L) {
          setLongNum2(other.getLongNum2());
        }
        if (other.getIntNum() != 0) {
          setIntNum(other.getIntNum());
        }
        if (other.getIntNum2() != 0) {
          setIntNum2(other.getIntNum2());
        }
        if (other.getDoubleNum() != 0D) {
          setDoubleNum(other.getDoubleNum());
        }
        if (other.getDoubleNum2() != 0D) {
          setDoubleNum2(other.getDoubleNum2());
        }
        if (other.getLocalDate() != 0L) {
          setLocalDate(other.getLocalDate());
        }
        if (other.getLocalDateTime() != 0L) {
          setLocalDateTime(other.getLocalDateTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.TestEntityOuterClass.TestEntity parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.TestEntityOuterClass.TestEntity) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name2_ = "";
      /**
       * <code>string name2 = 2;</code>
       * @return The name2.
       */
      public java.lang.String getName2() {
        java.lang.Object ref = name2_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name2_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name2 = 2;</code>
       * @return The bytes for name2.
       */
      public com.google.protobuf.ByteString
          getName2Bytes() {
        java.lang.Object ref = name2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name2 = 2;</code>
       * @param value The name2 to set.
       * @return This builder for chaining.
       */
      public Builder setName2(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name2 = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName2() {
        
        name2_ = getDefaultInstance().getName2();
        onChanged();
        return this;
      }
      /**
       * <code>string name2 = 2;</code>
       * @param value The bytes for name2 to set.
       * @return This builder for chaining.
       */
      public Builder setName2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name2_ = value;
        onChanged();
        return this;
      }

      private long longNum_ ;
      /**
       * <code>int64 longNum = 3;</code>
       * @return The longNum.
       */
      @java.lang.Override
      public long getLongNum() {
        return longNum_;
      }
      /**
       * <code>int64 longNum = 3;</code>
       * @param value The longNum to set.
       * @return This builder for chaining.
       */
      public Builder setLongNum(long value) {
        
        longNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 longNum = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongNum() {
        
        longNum_ = 0L;
        onChanged();
        return this;
      }

      private long longNum2_ ;
      /**
       * <code>int64 longNum2 = 4;</code>
       * @return The longNum2.
       */
      @java.lang.Override
      public long getLongNum2() {
        return longNum2_;
      }
      /**
       * <code>int64 longNum2 = 4;</code>
       * @param value The longNum2 to set.
       * @return This builder for chaining.
       */
      public Builder setLongNum2(long value) {
        
        longNum2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 longNum2 = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongNum2() {
        
        longNum2_ = 0L;
        onChanged();
        return this;
      }

      private int intNum_ ;
      /**
       * <code>int32 intNum = 5;</code>
       * @return The intNum.
       */
      @java.lang.Override
      public int getIntNum() {
        return intNum_;
      }
      /**
       * <code>int32 intNum = 5;</code>
       * @param value The intNum to set.
       * @return This builder for chaining.
       */
      public Builder setIntNum(int value) {
        
        intNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 intNum = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearIntNum() {
        
        intNum_ = 0;
        onChanged();
        return this;
      }

      private int intNum2_ ;
      /**
       * <code>int32 intNum2 = 6;</code>
       * @return The intNum2.
       */
      @java.lang.Override
      public int getIntNum2() {
        return intNum2_;
      }
      /**
       * <code>int32 intNum2 = 6;</code>
       * @param value The intNum2 to set.
       * @return This builder for chaining.
       */
      public Builder setIntNum2(int value) {
        
        intNum2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 intNum2 = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearIntNum2() {
        
        intNum2_ = 0;
        onChanged();
        return this;
      }

      private double doubleNum_ ;
      /**
       * <code>double doubleNum = 7;</code>
       * @return The doubleNum.
       */
      @java.lang.Override
      public double getDoubleNum() {
        return doubleNum_;
      }
      /**
       * <code>double doubleNum = 7;</code>
       * @param value The doubleNum to set.
       * @return This builder for chaining.
       */
      public Builder setDoubleNum(double value) {
        
        doubleNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double doubleNum = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearDoubleNum() {
        
        doubleNum_ = 0D;
        onChanged();
        return this;
      }

      private double doubleNum2_ ;
      /**
       * <code>double doubleNum2 = 8;</code>
       * @return The doubleNum2.
       */
      @java.lang.Override
      public double getDoubleNum2() {
        return doubleNum2_;
      }
      /**
       * <code>double doubleNum2 = 8;</code>
       * @param value The doubleNum2 to set.
       * @return This builder for chaining.
       */
      public Builder setDoubleNum2(double value) {
        
        doubleNum2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double doubleNum2 = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearDoubleNum2() {
        
        doubleNum2_ = 0D;
        onChanged();
        return this;
      }

      private long localDate_ ;
      /**
       * <code>int64 localDate = 9;</code>
       * @return The localDate.
       */
      @java.lang.Override
      public long getLocalDate() {
        return localDate_;
      }
      /**
       * <code>int64 localDate = 9;</code>
       * @param value The localDate to set.
       * @return This builder for chaining.
       */
      public Builder setLocalDate(long value) {
        
        localDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 localDate = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearLocalDate() {
        
        localDate_ = 0L;
        onChanged();
        return this;
      }

      private long localDateTime_ ;
      /**
       * <code>int64 localDateTime = 10;</code>
       * @return The localDateTime.
       */
      @java.lang.Override
      public long getLocalDateTime() {
        return localDateTime_;
      }
      /**
       * <code>int64 localDateTime = 10;</code>
       * @param value The localDateTime to set.
       * @return This builder for chaining.
       */
      public Builder setLocalDateTime(long value) {
        
        localDateTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 localDateTime = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearLocalDateTime() {
        
        localDateTime_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.TestEntity)
    }

    // @@protoc_insertion_point(class_scope:protocol.TestEntity)
    private static final proto.TestEntityOuterClass.TestEntity DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.TestEntityOuterClass.TestEntity();
    }

    public static proto.TestEntityOuterClass.TestEntity getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TestEntity>
        PARSER = new com.google.protobuf.AbstractParser<TestEntity>() {
      @java.lang.Override
      public TestEntity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TestEntity(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TestEntity> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TestEntity> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.TestEntityOuterClass.TestEntity getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_TestEntity_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_TestEntity_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)src/main/resources/proto/TestEntity.pr" +
      "oto\022\010protocol\"\276\001\n\nTestEntity\022\014\n\004name\030\001 \001" +
      "(\t\022\r\n\005name2\030\002 \001(\t\022\017\n\007longNum\030\003 \001(\003\022\020\n\010lo" +
      "ngNum2\030\004 \001(\003\022\016\n\006intNum\030\005 \001(\005\022\017\n\007intNum2\030" +
      "\006 \001(\005\022\021\n\tdoubleNum\030\007 \001(\001\022\022\n\ndoubleNum2\030\010" +
      " \001(\001\022\021\n\tlocalDate\030\t \001(\003\022\025\n\rlocalDateTime" +
      "\030\n \001(\003B\021\n\005protoZ\010protocolb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protocol_TestEntity_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_TestEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_TestEntity_descriptor,
        new java.lang.String[] { "Name", "Name2", "LongNum", "LongNum2", "IntNum", "IntNum2", "DoubleNum", "DoubleNum2", "LocalDate", "LocalDateTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
